project_id = "bmmkkdrguescudrymcsl"

[functions.text-to-speech]
verify_jwt = false

[functions.send-schedule-email]
verify_jwt = false

[functions.send-session-reminder]
verify_jwt = false

[functions.generate-session-insights]
verify_jwt = false