// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://bmmkkdrguescudrymcsl.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtbWtrZHJndWVzY3VkcnltY3NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIwNDQwMDMsImV4cCI6MjA0NzYyMDAwM30.NTWG90JT2WQLo7zwhsF_t9ZpdhfYt9Dr4Spf3giM56Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);